name: vimeo_player
description: Vimeo Player Flutter package.
version: 0.0.1
author: Prabhanu Gunaweera(prahack)
homepage: https://github.com/prahack/vimeo_player

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
